version: "3.9"
services:
  apache:
    build: .
    ports:
      - "8081:80"
    networks:
      local_net:
        ipv4_address: 173.18.0.2
  db:
    image: mysql/mysql-server:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=joomla
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      local_net:
        ipv4_address: 173.18.0.3

networks:
  local_net:
    driver: bridge
    ipam:
      config:
        - subnet: 173.18.0.0/24
          gateway: 173.18.0.1
